version       = "0.1.0"
author        = "Talos"
description   = "Talos agent binary"
license       = "MIT"
srcDir        = "src"
bin           = @["talos_agent"]
requires "nim >= 2.0.0"
requires "https://github.com/mrspaghatti/talos_core#v1.16.0"
requires "db_connector >= 0.1.0"
requires "illwill >= 0.4.0"
requires "dimscord >= 1.0.0"
requires "cligen >= 1.6.0"
requires "cdp >= 0.1.0"
requires "smtp >= 0.1.0"
switch("path", "src")

task test, "Run all tests":
  exec "nim c --path:src --threads:on -r tests/tagent_loop.nim"
  exec "nim c --path:src -r tests/tcli.nim"
  exec "nim c --path:src -r tests/test_shell_tool.nim"
  exec "nim c --path:src -r tests/test_bang.nim"
  exec "nim c --path:src --threads:on -r tests/tintegration.nim"
  exec "nim c --path:src -r tests/tdelegate_tool.nim"
  exec "nim c --path:src -r tests/tbench.nim"
  exec "nim c --path:src --threads:on -r tests/tweb_server.nim"
  exec "nim c --path:src -r tests/ttui_streaming.nim"
  exec "nim c --path:src -r tests/test_transcript.nim"
  exec "nim c --path:src -r tests/test_input_bar.nim"
  exec "nim c --path:src -r tests/test_discord_mocks.nim"
  exec "nim c --path:src -r tests/test_discord_commands.nim"
  exec "nim c --path:src -r tests/test_discord_bot.nim"
  exec "nim c --path:src --threads:on -r tests/test_e2e_discord.nim"
  exec "nim c --path:src -r tests/test_discord_config.nim"
  exec "nim c --path:src -r tests/test_thread_mapping.nim"
  exec "nim c --path:src -r tests/test_thread_reconnection.nim"
  exec "nim c --path:src --threads:on -r tests/test_daemon_delegation.nim"
  exec "nim c --path:src -r tests/test_session_alias.nim"
  exec "nim c --path:src -r tests/test_browser_tool.nim"
  exec "nim c --path:src -r tests/test_email_config.nim"
  exec "nim c --path:src -r tests/test_email_tool.nim"
  exec "nim c --path:src --threads:on -r tests/test_memory_tools.nim"
